server:
  port: 7001



eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false #表示不向注册中心注册自己
    fetch-registry: false  #false表示自己就是注册中心，我的职责就是维护服务实例,并不区检索服务
    service-url:
#      defaultZone: http://eureka7002.com:7002/eureka/ #集群版
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #单机版
  server:
    enable-self-preservation: false #关闭自我保护机制，及时关闭不可用的服务
    eviction-interval-timer-in-ms: 2000  #两秒内没有收到心跳就关闭服务
