server:
  port: 8004

spring:
  application:
    name: cloud-provider-payment
  cloud:  #使用zookeeper作为注册中心
    zookeeper:
      connect-string: 192.168.177.103:2181
      discovery:
        instanceHost: 192.168.177.1
        instance-port: 8004